### ISSUE TITLE
None of the Rapid7 blog examples work

### ISSUE THREAD

**Issue by jeanxpierre** [brandonprry/nexpose-sharp#3]
It appears that the examples were connected to the old code.  However, large parts of the code was deleted to start the rewrite.  Unfortunately, now the methods referenced in the blog are not relevant.

https://blog.rapid7.com/2012/01/13/communicating-and-integrating-with-nexpose-from-your-netmono-applications/

Are you going to re-add the methods, create new ones, or add the old code back?

Thanks for the help

**Comment by brandonprry** [comment]
For working Nexpose code, please see the Gray Hat C# repository. It's by no means an exhaustive library, but it is the basic building blocks and easily extensible.

https://github.com/brandonprry/gray_hat_csharp_code/tree/master/ch6_automating_nexpose
